#!/bin/bash

#echo "$(cat usage.text | awk '{print $1}')" | sed 's/[^0-9]*//g'
# du -sh capstone-project1-copy1/ > usage.text
echo "This script is used to check the directory useage"
read -p "Enter the dirctory path" path
read -p "Enter the size limit of directory in KB " size

du -sh $path > usage.text > usage.text
echo $(cat usage.text | awk '{print $1}')" | sed 's/[^0-9]*//g' > dir_size.text
echo "_____"

if [ $(cat dir_size.text) -lt $size ]
then
echo "it is ok"
else
echo "deangerous"
fi